#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.ts$")
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\n\033[36mPRE COMMIT HOOK\n"
printf "\033[36m  - Validating Javascript...\n"

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mInstalling missing dependencies...\033[0m"
  npm i yarn
  npx yarn
fi

for FILE in $STAGED_FILES
do
  "$ESLINT" "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "  \033[36m✓ ESLint Passed: $FILE\033[0m\n"
  else
    printf "  \033[41m✘ ESLint Failed: $FILE\033[0m\n"
    PASS=false
  fi
done

if ! $PASS; then
  printf "\n\n\033[31mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
fi
printf "\n\\033[36mPRE COMMIT HOOK SUCCESSFUL\n"

exit $?
